<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>txt_LoginSucess</name>
   <tag></tag>
   <elementGuidId>ebca1880-0f86-4f6a-90a3-4d67e5e8731f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#flash</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='flash']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>987caaf9-526f-4e36-a258-ca6b8f0dcae7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>flash</value>
      <webElementGuid>d1d26019-02ae-4173-98fe-36dac7231c60</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>flash success</value>
      <webElementGuid>e086ada1-db63-42aa-bb4e-83bbbf4b2320</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
            You logged into a secure area!
            ×
          </value>
      <webElementGuid>e39262a8-3765-4f1b-bb73-048790fb30db</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;flash&quot;)</value>
      <webElementGuid>31fc101c-d859-416b-abcd-556e74f5b702</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='flash']</value>
      <webElementGuid>90411842-dc1d-4e43-ae3f-e008cfc21d6d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='flash-messages']/div</value>
      <webElementGuid>0ef8f847-63ef-410e-be4a-5da07f64061f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Secure Area'])[1]/preceding::div[1]</value>
      <webElementGuid>200e9759-7f46-40e7-b75e-168ad3b89414</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Welcome to the Secure Area. When you are done click logout below.'])[1]/preceding::div[1]</value>
      <webElementGuid>c9ebbb69-165d-4900-ba6d-a773963bf3eb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='You logged into a secure area!']/parent::*</value>
      <webElementGuid>9008fae5-2be7-4a94-b5ee-02dc00979b6e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div</value>
      <webElementGuid>06f6aec1-c183-4e06-9348-68ec9bb5032f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'flash' and (text() = '
            You logged into a secure area!
            ×
          ' or . = '
            You logged into a secure area!
            ×
          ')]</value>
      <webElementGuid>b1c26d88-e88e-4ee6-8e20-1910fe2c5531</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
